#' @title Canonical PPT Defaults
#' @description Single backend source of truth for PowerPoint defaults.

build_ppt_defaults <- function(order = c("ppt", "runtime")) {
    order <- match.arg(order)
    defaults <- list(
        ppt_layout_mode = "template",
        ppt_template_path = file.path("data", "template_16_9.pptx"),
        ppt_master = "Office Theme",
        summary_slide_layout = "Title and Content",
        detail_slide_layout = "Title Only",
        slide_header_mode = "template_placeholder",
        slide_header_placeholder_fallback = TRUE,
        slide_header_title_placeholder_type = "title",
        slide_header_title_placeholder_label = "DRB_Title_Placeholder",
        slide_header_bullet_placeholder_type = "body",
        slide_header_bullet_placeholder_label = "DRB_Body_Placeholder",
        slide_title = "[DM] DRB Statistical Auto Report",
        ppt_font_family = "Malgun Gothic",
        slide_header_left = 0.2952756,
        slide_header_title_top = 0.3740157,
        slide_header_title_width = 11.266404,
        slide_header_title_height = 0.5314961,
        slide_header_title_font_size = 28,
        slide_header_bullet_top = 1.0314961,
        slide_header_bullet_width = 12.598425,
        slide_header_bullet_height = 0.6377953,
        slide_header_bullet_font_size = 13,
        slide_header_bullet_bold = TRUE,
        slide_header_bullet_color = "#333333",
        summary_header_bullet_top = 1.0314961,
        summary_header_bullet_height = 0.6377953,
        summary_header_bullet_font_size = 13,
        slide_header_title_color = "#111111",
        slide_bullet_symbol = "\u25A0",
        slide_max_bullets = 2L,
        slide_affiliation = "",
        slide_affiliation_left = 9.0420079,
        slide_affiliation_top = 7.0551181,
        slide_affiliation_width = 2.7559055,
        slide_affiliation_height = 0.2598425,
        slide_affiliation_font_size = 12,
        slide_affiliation_color = "#7F7F7F",
        suggested_slide_title = "[DM] DRB Suggested Review",
        summary_slide_bullets = c(
            "REF: {ref} / TARGET: {target} | Threshold: {sigma_threshold}",
            "TREND: plot \uC218\uB3D9 \uBD80\uCC29 / \uBE44\uACE0: \uC218\uB3D9 \uC791\uC131"
        ),
        suggested_summary_slide_bullets = c(
            "Suggested: |Sigma| > {sigma_threshold} | {selected_count} MSR ({summary_page}/{summary_total_pages})",
            "REF: {ref} / TARGET: {target}"
        ),
        detail_slide_bullets = c(
            "Category: {category} | Showing MSR {detail_selected_start}-{detail_selected_end} of {category_msr_count}",
            "REF: {ref} / TARGET: {target} | Threshold: {sigma_threshold}"
        ),
        summary_rows_per_slide = 15L,
        detail_top_n = 8L,
        detail_group_by = "Category2",
        ppt_category_scope = NULL,
        suggested_ppt_enabled = TRUE,
        summary_category_columns = c("Category1", "Category2", "Category3"),
        summary_font_size = 8,
        summary_header_fill = "#4D4D4D",
        summary_header_color = "#FFFFFF",
        summary_border_color = "#CCCCCC",
        summary_highlight_fill = "#FFEBEE",
        summary_highlight_color = "#C62828",
        summary_category_fill = "#F2F2F2",
        summary_category_color = "#243B53",
        summary_reason_fill = "#F7F7F7",
        summary_reason_color = "#333333",
        summary_msr_col_width = 2.6,
        summary_selected_by_col_width = 0.9,
        summary_category_col_width = 0.55,
        summary_item_col_width = 1.70,
        summary_value_col_width = 0.55,
        summary_diff_col_width = 0.65,
        summary_result_col_width = 0.70,
        summary_trend_col_width = 3.80,
        summary_note_col_width = 2.44,
        summary_table_left = 0.32,
        summary_table_top = 1.68,
        summary_table_width = 12.69,
        summary_table_height = 5.32,
        goobae_slide_enabled = TRUE,
        goobae_slide_layout = "Title Only",
        goobae_slide_bullets = c(
            "GOOBAE: WL trend | Showing {goobae_selected_start}-{goobae_selected_end} of {goobae_group_count}",
            "REF: {ref} / TARGET: {target} | Threshold: {sigma_threshold}"
        ),
        goobae_slots_per_slide = 12L,
        goobae_category1_header_height = 0.32,
        goobae_category2_header_height = 0.28,
        goobae_plot_padding_x = 0.05,
        goobae_plot_padding_y = 0.06,
        goobae_y_label_width = 0.34,
        goobae_y_label_gap = 0.02,
        goobae_y_label_font_size = 4.0,
        goobae_y_label_font_face = "bold",
        goobae_y_label_dpi = 600L,
        goobae_y_label_min_gap = 0.18,
        goobae_header_font_size = 8.5,
        goobae_axis_text_size = 4.8,
        goobae_point_enabled = FALSE,
        goobae_point_size = 1.2,
        goobae_line_size = 0.70,
        detail_grid_ncol = 4L,
        detail_grid_nrow = 2L,
        slide_width = 13.33,
        slide_height = 7.5,
        margin_top = 1.68,
        margin_left = 0.32,
        margin_right = 0.32,
        margin_bottom = 0.50,
        detail_plot_gap = 0.08,
        detail_label_show_field = TRUE,
        detail_label_height = 0.25,
        detail_cell_padding = 0.04,
        detail_label_plot_gap = 0.03,
        detail_plot_top_inset = 0.03,
        detail_label_font_size = 9,
        detail_header_font_size = 10,
        detail_label_up_color = "#D62728",
        detail_label_down_color = "#2CA02C",
        detail_label_neutral_color = "#8C8C8C",
        detail_label_text_color = "#333333",
        detail_header_row_fill = "#E0E0E0",
        detail_label_row_fill = "#F2F2F2",
        detail_table_border_color = "#D9D9D9",
        detail_table_border_width = 0.5,
        detail_legend_show = TRUE,
        detail_legend_top_offset = 0.05,
        detail_legend_height = 0.24,
        detail_legend_font_size = 10,
        detail_legend_gap_spaces = "    ",
        detail_sigma_font_size = 8,
        detail_sigma_color = "#808080",
        jitter_width = 0.2,
        jitter_alpha = 0.6,
        jitter_size = 1.5,
        mean_point_size = 3,
        title_size = 11,
        axis_x_angle = 30,
        axis_text_size = 10,
        axis_title_size = 9,
        plot_dpi = 150,
        color_palette = "Set1",
        up_color = "red",
        down_color = "blue",
        detail_plot_mode = "composite_v1",
        detail_progress_log_every = 0L,
        composite_row_heights = c(1.00, 1.00, 1.00),
        composite_bottom_split = c(1.25, 1.75),
        radius_scatter_alpha = 0.70,
        radius_scatter_size = 1.1,
        radius_scatter_max_points_per_side = 2000L,
        radius_scatter_trim_iqr = FALSE,
        radius_scatter_show_mean = FALSE,
        radius_scatter_border_color = "#666666",
        radius_scatter_border_alpha = 0.45,
        radius_scatter_border_width = 0.05,
        radius_ref_color = "#2d74b3",
        radius_tgt_color = "#de2d26",
        radius_mean_line_width = 0.45,
        radius_mean_line_alpha = 0.90,
        radius_mean_label_digits = 2L,
        radius_mean_label_size = 2.1,
        radius_mean_label_y_offset = 0.025,
        radius_mean_label_color = "#666666",
        radius_mean_label_halo_color = "#FFFFFF",
        radius_mean_label_halo_alpha = 0.80,
        radius_mean_label_halo_width = 0.35,
        rootid_avg_point_size = 2.2,
        rootid_avg_point_border_color = "#666666",
        rootid_avg_point_border_alpha = 0.80,
        rootid_avg_point_border_width = 0.30,
        rootid_avg_line_alpha = 0.45,
        rootid_avg_y_expand_mult = 0.16,
        rootid_avg_axis_x_angle = 70,
        rootid_avg_axis_text_size = 6,
        rootid_avg_title_size = 8,
        cdf_ref_color = "#2d74b3",
        cdf_tgt_color = "#de2d26",
        cdf_line_size = 0.8,
        cdf_title_size = 8,
        cdf_max_points_per_side = 1000L,
        wf_map_point_size = 3.2,
        wf_map_stroke = 0.2,
        wf_map_stroke_color = "#666666",
        wf_map_color_mode = "percentile",
        wf_map_percentiles = c(0, 0.25, 0.50, 0.75, 0.99),
        wf_map_percentile_colors = c("#1B9E4B", "#4EA3D8", "#fed339", "#F28E2B", "#D62728"),
        wf_map_low_color = "#2166AC",
        wf_map_mid_color = "#F7F7F7",
        wf_map_high_color = "#B2182B",
        wf_map_midpoint = NA_real_,
        wf_map_coordinate_mode = "wafer_grid",
        wf_map_panel_arrangement = "auto",
        wf_map_force_square_display = TRUE,
        wf_map_fill_available_space = TRUE,
        wf_map_show_axes = FALSE,
        wf_map_missing_fill = NA_character_,
        wf_map_constant_fill = "#4EA3D8",
        wf_map_outline_color = NA_character_,
        wf_map_value_cache_max_cells = 5000000L,
        wf_map_title_size = 6,
        wf_map_strip_text_size = 3.8,
        wf_map_strip_text_color = "#666666",
        wf_map_panel_spacing_pt = 0,
        wf_map_axis_text_size = 4.5,
        wf_map_axis_tick_linewidth = 0.15
    )

    if (identical(order, "runtime")) {
        sigma_keys <- c("detail_sigma_font_size", "detail_sigma_color")
        legend_keys <- c(
            "detail_legend_show", "detail_legend_top_offset",
            "detail_legend_height", "detail_legend_font_size",
            "detail_legend_gap_spaces"
        )
        detail_keys <- c(sigma_keys, legend_keys)
        base_names <- names(defaults)
        insertion_index <- match("detail_legend_show", base_names) - 1L
        runtime_names <- append(
            base_names[!base_names %in% detail_keys],
            detail_keys,
            after = insertion_index
        )
        defaults <- defaults[runtime_names]
    }

    defaults
}
